import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
	await page.goto('https://anc.ua/');
	await page.getByRole('button', { name: 'Так' }).click();
	await page.getByRole('textbox', { name: 'Я шукаю' }).click();
	await page.getByRole('textbox', { name: 'Я шукаю' }).fill('аден');
	await page.getByRole('link', { name: 'аденомак 6 товара' }).click();
	await page.getByTitle('Аденомак 500 таблетки №20').click();
	await page.getByRole('button', { name: 'cart_white Додати у кошик' }).click();
	await page.getByRole('button', { name: '+' }).first().click();
	await page.getByRole('button', { name: '+' }).nth(1).click();
	await page.getByRole('button', { name: 'arrow_thin_left' }).click();
	await page.getByRole('button', { name: 'catalog Каталог товарів' }).click();
	await page.getByRole('link', { name: 'Препарати для очей і вух' }).click();
	await page.getByRole('link', { name: 'Препарати для очей та вуха' }).first().click();
	await page.locator('#product-55269').getByRole('button', { name: 'cart_white Купити' }).click();
	await page.getByRole('button', { name: 'arrow_thin_left' }).click();
	await page.getByRole('link', { name: 'Cart Кошик' }).click();
	await page.getByRole('button', { name: 'Так' }).click();
	await page.locator('.padding-tb-15 > div:nth-child(2) > button').first().click();
	await page.locator('.padding-tb-15 > div:nth-child(2) > button').first().click();
	await page.locator('.padding-tb-15 > div:nth-child(2) > button').first().click();
	await page.locator('div:nth-child(3) > div:nth-child(2) > button').click();
	await page.getByText('Товари у кошику').click();
	await page.getByRole('button', { name: 'Оформити замовлення' }).click();
	await page.getByRole('link', { name: 'Редагувати' }).click();
	await page.locator('div').filter({ hasText: /^Упаковка2$/ }).getByRole('button').first().click();
	await page.locator('div').filter({ hasText: /^блістер1$/ }).getByRole('button').first().click();
});